server:
  port: 8183

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/im?serverTimezone=Hongkong&useSSL=false&useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    database: 2
    host: localhost
    port: 6379
#    password: liaoin_pm
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  session:
    store-type: none

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


surpassm:
  security:
    o-auth2:
      clients[0]:
        clientId: user_1
        clientIdSecret: 123456
      clients[1]:
        clientId: user_2
        clientIdSecret: 123456

    login-type: JSON
#      登陆页面设置
    no-verify[0]: /swagger-**
    no-verify[1]: /images/**
    no-verify[2]: /webjars/**
    no-verify[3]: /v2/api-docs**
    no-verify[4]: /swagger-resources/configuration/ui**
    no-verify[5]: /swagger-resources/configuration/security**
    no-verify[6]: /websocket/socketServer.ws**
    no-verify[7]: /sockjs/socketServer.ws**
#    用户名密码登录请求处理url
    default-login-processing-url-from: /authentication/form
#    default-property-inclusion: NON_NULL
